### PR TITLE
Condition for SYSLIN allocation

### PR DESCRIPTION
**Pull request by dennis-behm**
This is related to issue #23

### CODE REVIEW

**Comment by drbruce-git** [comment]
@dennis-behm The fix as written causes the MortgageApplication build to throw a NullPointerException.  After fixing the NPE half of the LinkEdits failed with a RC=12 because the object deck was not being passed in the temporary dataset.  I found that this code fixes the issue for MortgageApplication.  Note the middle condition change.
```
if (props.debug && linkDebugExit && doLinkEdit.toBoolean()){
    compile.dd(new DDStatement().name("SYSLIN").dsn("${props.cobol_objPDS}($member)").options('shr').output(true))
} else if (doLinkEdit && doLinkEdit.toBoolean() && ( !linkEditStream || linkEditStream.isEmpty())) {
    compile.dd(new DDStatement().name("SYSLIN").dsn("&&TEMPOBJ").options(props.cobol_tempOptions).pass(true))
} else {
    compile.dd(new DDStatement().name("SYSLIN").dsn("${props.cobol_objPDS}($member)").options('shr').output(true))
}
```
Please amend your solution and perhaps retest your application and MortgageApplication to make sure both cases work.

Also why is this a Cobol only solution?  Shouldn't it be ported to any language script that does a link edit?  Should there be some sort of refactoring done to share this feature?

**Comment by dennis-behm** [comment]
@drbruce-git I performed several test with MortgageApplicationV2/Mortgage-Application. Probably, due to my modified application and build-conf, I did not see the NPE. What caused the NPE on your side? I will run a new set of tests today.

Agreed, that the debugging support should be ported to all other languages!

**Comment by drbruce-git** [comment]
@dennis-behm Your condition began with `linkEditStream.isEmpty() ` without doing a null check on linkEditStream which was assigned the value for property `cobol_linkEditStream` which does not exist in [MortgageApplicationV2/MortgageApplication/application-conf/cobol.properties](https://github.com/IBM/dbb/blob/edb71bc252168dc312d39f56ace5a1ad5255a6e5/Build/MortgageApplicationV2/MortgageApplication/application-conf/Cobol.properties).  I noticed that you added the property to the `zAppBuild/application-conf/cobol.properties` so it might be you had been testing with it with your version of MortgageApplication.

Going forward I think any enhancement requiring a change to application-conf should raise a warning on backward compatibility and will need to be tested with that in mind.

**Comment by drbruce-git** [comment]
Closing this pull request as zAppBuild has been moved to https://github.com/IBM/dbb-zappbuild.  @dennis-behm this change has already been implemented in the new location so no need to recreate.

**Pull request closed without merging**
