### PR TITLE
Bugfix on PackageBuildOutputs on parsing fullBuild Log

### PR DESCRIPTION
**Pull request by gcavalcante**
Hi, I'm currently building a CI/CD for a mainframe project in Brazil.

Our DBB server was down last week, so I started working with fullbuild on our pipeline. Unfortunately when we package the artifacts a error emerged:

` Read build report data from /u/gds/gabcavl/workspace/ffac537e_1643646053/result/build.20220131.012121.021/BuildReport.json
 Removing Output Records without deployType or with deployType=ZUNIT-TESTCASE 
Caught: java.lang.NullPointerException: Cannot get property 'label' on null object
java.lang.NullPointerException: Cannot get property 'label' on null object
        at PackageBuildOutputs.run(PackageBuildOutputs.groovy:121)`

It occurs because BuildReport.json for fullBuild does not have a dbbserver entry with BUILD_RESULT, like below:
`
        {
            "id": "BUILD_RESULT_1",
            "label": "build.20220128.110111.001",
            "type": "BUILD_RESULT",
            "url": "https://10.0.10.139:9443/dbb/rest/buildResult/3796",
            "group": "dbb-tests-main"
        },
`

This PR adds static names for label and buildGroup, but I personally don't know if it is the best strategy.

### CODE REVIEW

**Comment by drbruce-git** [comment]
@dennis-behm  can you review this pull request?

**Comment by drbruce-git** [comment]
@gcavalcante  can you email your DCO statement as outlined in https://github.com/IBM/dbb/blob/main/CONTRIBUTIONS.md so that we can consider merging your changes?

**Review by dennis-behm — CHANGES_REQUESTED** [review]
Gabriel @gcavalcante, can you please have another look to your code?

This is currently not functioning. Like in Java, you need to define the variable outside of a if clause.  Additionally, the buildGroup is not used in the script. I think, we can remove it.
Also setting the tarFileName still references the DBB BuildRecord.

```def String tarFileLabel
	if (buildInfo.size() == 0){
		// set a default when no dbb buildInfo record is present
		tarFileLabel = "fullBuild"
	}
	else {
		// obtain label from buildInfo record
		tarFileLabel = buildInfo[0].label
	}
	def String tarFileName = (props.tarFileName) ? props.tarFileName : "${tarFileLabel}.tar"
```

Dennis

**Comment by gcavalcante** [comment]
@dennis-behm thanks for the review, you're right about declaration scope. But it worked on my tests..

Anyway, I changed the code to get rid of buildGroup and remove the first if, doing the declaration outside if scope.

**Comment by dennis-behm** [comment]
Hey @gcavalcante, apologies for the delay in getting back to you and also that I bypassed your PR with my updates to the script.
Have you sent the DCO agreement to Dan as outlined in the contributions of this project?

**Pull request merged**
