### PR TITLE
Compute build parameters on updated branch naming conventions

### PR DESCRIPTION
**Pull request by dennis-behm**
As indicated in #193, the pipeline backend scripts need to use shorter branch names.

This PR is refreshing the computation of the build conventions:

* Feature branches are prefixed with an `F`.
* Epic branches are prefixed with `E`.
* Hotfix branches are prefixed with `H`.
* Release Maintenance branches are prefixed with `R`.

| branch name  | computed hlq | 
| -------------  | ------------ |
|feature/42-new-mortgage-calculation |PIPELINE.MORTGAGE.F42 |
|feature/new-mortgage-calculation |PIPELINE.MORTGAGE.FNMC |
|feature/newmortgagecalculation |PIPELINE.MORTGAGE.FNEWMORT |
|release/rel-2.0.1  | PIPELINE.MORTGAGE.R201 | 
|hotfix/rel-2.0.1/52-fix-mortgage-calculation |PIPELINE.MORTGAGE.R201.H52 |
|epic/ai-fraud-detection |PIPELINE.MORTGAGE.EAFD |
|feature/ai-fraud-detection/54-introduce-ai-model-to-mortgage-calculation |PIPELINE.MORTGAGE.EAFD.F54 |

### CODE REVIEW

**Comment by dennis-behm** [comment]
Had a chat with @M-DLB about it, who is proposing a more simpler layout for the branches.

Instead of multi segment, he is proposing 
* treating all Feature branches similar, and just prefix with an `F`.
* treating all Hotfix branches similar, and just prefix with an `H`.

**Comment by dennis-behm** [comment]
@M-DLB 

I have updated the scripts and followed your recommendations to name the feature branches.


The currently implemented layout is listed below. `(*)` identifies the changed names to the initial conventions that I proposed in the PR. 

| branch name  | computed hlq | 
| -------------  | ------------ |
|feature/42-new-mortgage-calculation |PIPELINE.MORTGAGE.F42 |
|feature/new-mortgage-calculation |PIPELINE.MORTGAGE.FNMC |
|feature/newmortgagecalculation |PIPELINE.MORTGAGE.FNEWMORT |
|release/rel-2.0.1  | PIPELINE.MORTGAGE.R201 | 
|hotfix/rel-2.0.1/52-fix-mortgage-calculation |PIPELINE.MORTGAGE.H52 (*) |
|epic/ai-fraud-detection |PIPELINE.MORTGAGE.EAFD |
|feature/ai-fraud-detection/54-introduce-ai-model-to-mortgage-calculation |PIPELINE.MORTGAGE.F54 (*) |

**Comment by dennis-behm** [comment]
Please note that this PR improves the computation of the build parameter `mainBuildBranch` to set the origin branch correctly for feature and hot fix branches.

**Review by M-DLB — APPROVED** [review]
Approved, thank you

**Pull request merged**
