### PR TITLE
Merge Git ISPF Client fork with base repository IBM/dbb

### PR DESCRIPTION
**Pull request by campagboy**
I decided to check the Git ISPF Client and make sure it was up to date and in good order. It needed a bit of a clean up. Please can you merge my fork with Master.

### CODE REVIEW

**Comment by drbruce-git** [comment]
@campagboy  looks like there are conflicts that have to be resolved before this can be pushed.

**Comment by campagboy** [comment]
No idea why. Changed the code a bit, not much. Looks the bloody same to
me..




So this is the future?

Will try and work out what to do to make Git think it is OK. Might take a
while



Regards
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
   Liam Doherty                                                   1060 Hay Street                          
                                                                                                           
   Architect for                                                  West Perth, 6005                         
   EWM and SCLM                                                                                            
   on System z                                                                                             
                                                                                                           
   IBM Systems                                                    Australia                                
                                                                                                           
   Australia                                                                                               
   Development                                                                                             
   Lab (ADL)                                                                                               
                                                                                                           
   Phone:        +61-8-9261-8627                                                                           
                                                                                                           
   Tie-Line:     701 8627                                                                                  
                                                                                                           
   e-mail:       ***@***.***                                                                       
                                                                                                           






From:	"Dan Bruce" ***@***.***>
To:	"IBM/dbb" ***@***.***>
Cc:	"LIAM" ***@***.***>, "Mention"
            ***@***.***>
Date:	13/08/2021 07:51 PM
Subject:	[EXTERNAL] Re: [IBM/dbb] Merge Git ISPF Client fork with base
            repository IBM/dbb (#89)



@campagboy looks like there are conflicts that have to be resolved before
this can be pushed. — You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe. Triage
notifications on 


@campagboy looks like there are conflicts that have to be resolved before
this can be pushed.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by drbruce-git** [comment]
@campagboy  It looks like three files that you are replacing have different line padding i.e. padded to 80 columns vs no padding.  I am having difficulty determining from the Git Web Comparison editor which is padded and which is not.  I will let you investigate that.  :^)

The three files are:
bgzrepos.rexx
bgzuslst.rexx
bgzdbbsc.gml

**Comment by campagboy** [comment]
Yeah, got it was those files. No idea what thinks what is different. I
changed some code. Frustrating. Will try and work it out or resign,
whatever comes first...

Regards
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
                                                                                                           
   Liam Doherty                                                   1060 Hay Street                          
                                                                                                           
   Architect for                                                  West Perth, 6005                         
   EWM and SCLM                                                                                            
   on System z                                                                                             
                                                                                                           
   IBM Systems                                                    Australia                                
                                                                                                           
   Australia                                                                                               
   Development                                                                                             
   Lab (ADL)                                                                                               
                                                                                                           
   Phone:        +61-8-9261-8627                                                                           
                                                                                                           
   Tie-Line:     701 8627                                                                                  
                                                                                                           
   e-mail:       ***@***.***                                                                       
                                                                                                           






From:	"Dan Bruce" ***@***.***>
To:	"IBM/dbb" ***@***.***>
Cc:	"LIAM" ***@***.***>, "Mention"
            ***@***.***>
Date:	16/08/2021 09:05 PM
Subject:	[EXTERNAL] Re: [IBM/dbb] Merge Git ISPF Client fork with base
            repository IBM/dbb (#89)



@campagboy It looks like three files that you are replacing have different
line padding i.e. padded to 80 columns vs no padding. I am having
difficulty determining from the Git Web Comparison editor which is padded
and which is not. I will 


@campagboy It looks like three files that you are replacing have different
line padding i.e. padded to 80 columns vs no padding. I am having
difficulty determining from the Git Web Comparison editor which is padded
and which is not. I will let you investigate that. :^)


The three files are:
bgzrepos.rexx
bgzuslst.rexx
bgzdbbsc.gml


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by campagboy** [comment]
@drbruce-git I deleted all the bits that were not the recent changes and resolved to conflicts. Please Merge with Master. I will then clone and check it all looks good.

**Pull request merged**
