### PR TITLE
Fix wazideploy-deploy.sh and wazideploy-evidence.sh backend scripts for relative workspace scenario

### PR DESCRIPTION
**Pull request by dennis-behm**
This is fixing the scenario when a relative path is used to invoke the wazideploy-deploy.sh script. See reported defect #194 

It simplifies the validation of the workspace parameter.

### CODE REVIEW

**Comment by M-DLB** [comment]
@dennis-behm Do you also see the problem with wazideploy-evidence.sh ?

**Comment by dennis-behm** [comment]
@M-DLB - thanks for pointing me to the evidence script. Yes it has the same problem to append the deployPkgDir twice.

```
wazideploy-evidence.sh: [INFO] **************************************************************
wazideploy-evidence.sh: [INFO] ** Start Wazi Deploy evidence reporting on HOST/USER: z/OS ZT01 04.00 02 8561/BPXROOT
wazideploy-evidence.sh: [INFO] **               Working Directory: /u/ado/workspace/MortgageApplication/main/build-20231122.2/deployPkgDir
wazideploy-evidence.sh: [INFO] **                     Output File: /u/ado/workspace/MortgageApplication/main/build-20231122.2/deployPkgDir/deployPkgDir/deployment-report.html
wazideploy-evidence.sh: [INFO] **                   Evidence File: /u/ado/workspace/MortgageApplication/main/build-20231122.2/deployPkgDir/deployPkgDir/evidence.yaml
wazideploy-evidence.sh: [INFO] **************************************************************
```

Will fix it in this PR as well.

**Comment by dennis-behm** [comment]
@M-DLB - this is ready for review.

Just one comment/question - what is the purpose of storing the outputs of the evidence process in the subfolder `/deploy/evidences` and the generated deployment report in `deploy`?

```
#
# Default name of the wazideploy **evidence file** file
wdEvidenceFileName="deploy/evidences/evidence.yaml"
...
#
# Default path of wazideploy evidence output file
# wdOutputFile=
wdOutputFile="deploy/deployment-report.html"
```

**Comment by M-DLB** [comment]
> @M-DLB - this is ready for review.
> 
> Just one comment/question - what is the purpose of storing the outputs of the evidence process in the subfolder `/deploy/evidences` and the generated deployment report in `deploy`?
> 
> ```
> #
> # Default name of the wazideploy **evidence file** file
> wdEvidenceFileName="deploy/evidences/evidence.yaml"
> ...
> #
> # Default path of wazideploy evidence output file
> # wdOutputFile=
> wdOutputFile="deploy/deployment-report.html"
> ```

It is easier when using wazideploy-evidence, as it is searching for the evidence YAML files in a given directory (i.e., you don't pass the path to the evidence file, but the path to the directory which contain the evidence file). The output file doesn't need to be in that evidence subfolder.

**Review by M-DLB — APPROVED** [review]
It looks good, thank you!

**Pull request merged**
